<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="tests.Tests" duration-ms="39926" started-at="2021-04-17T13:47:17 ART" finished-at="2021-04-17T13:47:57 ART">
    <groups>
    </groups>
    <test name="Command line test" duration-ms="39926" started-at="2021-04-17T13:47:17 ART" finished-at="2021-04-17T13:47:57 ART">
      <class name="tests.Tests">
        <test-method status="PASS" signature="SetUp()[pri:0, instance:tests.Tests@5702b3b1]" name="SetUp" is-config="true" duration-ms="11761" started-at="2021-04-17T13:47:17 ART" finished-at="2021-04-17T13:47:29 ART">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUp -->
        <test-method status="FAIL" signature="pruebaDos()[pri:0, instance:tests.Tests@5702b3b1]" name="pruebaDos" duration-ms="5914" started-at="2021-04-17T13:47:29 ART" finished-at="2021-04-17T13:47:34 ART">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at tests.Tests.pruebaDos(Tests.java:46)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:110)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- pruebaDos -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:tests.Tests@5702b3b1]" name="tearDown" is-config="true" duration-ms="4157" started-at="2021-04-17T13:47:34 ART" finished-at="2021-04-17T13:47:39 ART">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="SetUp()[pri:0, instance:tests.Tests@5702b3b1]" name="SetUp" is-config="true" duration-ms="8645" started-at="2021-04-17T13:47:39 ART" finished-at="2021-04-17T13:47:47 ART">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUp -->
        <test-method status="PASS" signature="pruebaUno()[pri:0, instance:tests.Tests@5702b3b1]" name="pruebaUno" duration-ms="5264" started-at="2021-04-17T13:47:47 ART" finished-at="2021-04-17T13:47:53 ART">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- pruebaUno -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:tests.Tests@5702b3b1]" name="tearDown" is-config="true" duration-ms="4107" started-at="2021-04-17T13:47:53 ART" finished-at="2021-04-17T13:47:57 ART">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- tests.Tests -->
    </test> <!-- Command line test -->
  </suite> <!-- tests.Tests -->
</testng-results>
